# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/pg_management_db
spring.datasource.username=postgres
spring.datasource.password=kmp15072004
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000

# Mail / SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=krish.patel0776@gmail.com
spring.mail.password=hggzqbheihyhdgif
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
app.mail.from=krish.patel0776@gmail.com
# Mail switch: set to 'true' to send real emails, or 'false' to disable sending during development
app.mail.enabled=false
app.frontend.url=http://localhost:3000